OS: centos
ImageId: ami-02dc4c6b
InstanceType: t2.medium
KeyPair: dbmi_development
IPAddress: null
ChefRole: null
AnsiblePlaybook: rc-pcori-pmsdn/transmart.yml
AnsibleGroup: transmart
environment: develop
InstanceName: transmart-dev
StackName: transmart-dev
cloudtype: aws
SecGroups:
    - transmartdev
AppServerAvailabilityZones:
    # us-east-1b and us-east-1c smell funny, skip those...
    - us-east-1a
    - us-east-1c
    - us-east-1d
LoadBalancer: false
AutoScalingGroupMaxSize: 1
AutoScalingGroupMinSize: 1
Tags:
 ansiblegroup: transmart
 environment: develop
